export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const SELECT_SCHEDULE = 'SELECT_SCHEDULE';

export const CHANGE_SCHEDULE_STATUS = 'CHANGE_SCHEDULE_STATUS';

export const SET_SCHEDULE_EVENTS = 'SET_SCHEDULE_EVENTS';

export const SET_SCHEDULE_GROUPS = 'SET_SCHEDULE_GROUPS';

export const CHANGE_BEGIN_DATE = 'CHANGE_BEGIN_DATE';

export const CHANGE_END_DATE = 'CHANGE_END_DATE';

export const SELECT_GROUPER_PERIOD = 'SELECT_GROUPER_PERIOD';